stages:
    - static
    - test
    - deploy

unit-test:
    stage: test
    image: python:3.9
    script:
        - pip install pytest pytest-cov
        - python -m pytest --cov-report=html --cov=src .
    artifacts:
        paths:
            - coverage
        expire_in: 30 days
    only:
        - merge_requests

mypy:
    stage: static
    image: python:3.9
    script:
        - pip install mypy
        - mypy src
    allow_failure: true
    only:
        - merge_requests

flake8:
    stage: static
    image: python:3.9
    script:
        - pip install flake8
        - flake8
    allow_failure: true
    only:
        - merge_requests

pylint:
    stage: static
    image: python:3.9
    script:
        - pip install pylint
        - find . -type f -name "*.py" | xargs pylint
    allow_failure: true
    only:
        - merge_requests

black:
    stage: static
    image: python:3.9
    script:
        - pip install black
        - black --check .
    allow_failure: true
    only:
        - merge_requests

isort:
    stage: static
    image: python:3.9
    script:
        - pip install isort
        - isort . --check-only
    allow_failure: true
    only:
        - merge_requests

pages:
  stage: deploy
  image: alpine
  script:
    - quarto render index.qmd
    - mv doc/seminaire-dms-oct-2022/slides public
  artifacts:
    paths:
      - public