stages:
    - test

unit-test:
    stage: test
    image: python:3.9
    script:
        - pip install pytest pytest-cov
        - python -m pytest --cov-report=html --cov=src .
    artifacts:
        paths: 
            - coverage
        expire_in: 30 days

type-test:
    stage: test
    image: python:3.9
    script:
        - pip install mypy
        - mypy src
    allow_failure: true

lint_test:
    stage: test
    image: python:3.9
    script:
        - pip install flake8
        - flake8
    allow_failure: true