stages:
    - static
    - test

unit-test:
    stage: test
    image: python:3.9
    script:
        - pip install pytest pytest-cov
        - python -m pytest --cov-report=html --cov=src .
    artifacts:
        paths:
            - coverage
        expire_in: 30 days
    only:
        - merge_requests

mypy:
    stage: static
    image: python:3.9
    script:
        - pip install mypy
        - mypy src
    allow_failure: true
    only:
        - merge_requests

flake8:
    stage: static
    image: python:3.9
    script:
        - pip install flake8
        - flake8
    allow_failure: true
    only:
        - merge_requests

pylint:
    stage: static
    image: python:3.9
    script:
        - find . -type f -name "*.py" | xargs pylint
    allow_failure: true
    only:
        - merge_requests

black:
    stage: static
    image: python:3.9
    script:
        - black --check
    allow_failure: true
    only:
        - merge_requests

isort:
    stage: static
    image: python:3.9
    script:
        - isort . --check-only
    allow_failure: true
    only:
        - merge_requests
