stages:
    - static
    - test
    - deploy

variables:
  GIT_SSL_NO_VERIFY: "1"

unit-test:
    stage: test
    image: python:3.9
    script:
        - pip install pytest pytest-cov
        - python -m pytest --cov-report=html --cov=src .
    artifacts:
        paths:
            - coverage
        expire_in: 30 days
    only:
        - merge_requests

mypy:
    stage: static
    image: python:3.9
    script:
        - pip install mypy
        - mypy src
    allow_failure: true
    only:
        - merge_requests

flake8:
    stage: static
    image: python:3.9
    script:
        - pip install flake8
        - flake8
    allow_failure: true
    only:
        - merge_requests

pylint:
    stage: static
    image: python:3.9
    script:
        - pip install pylint
        - find . -type f -name "*.py" | xargs pylint
    allow_failure: true
    only:
        - merge_requests

black:
    stage: static
    image: python:3.9
    script:
        - pip install black
        - black --check .
    allow_failure: true
    only:
        - merge_requests

isort:
    stage: static
    image: python:3.9
    script:
        - pip install isort
        - isort . --check-only
    allow_failure: true
    only:
        - merge_requests

package:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY/$CI_PROJECT_PATH:$CI_COMMIT_TAG

pages:
  stage: deploy
  image: inseefrlab/onyxia-r-minimal
  script:
    # - Rscript -e "install.packages(c('rmarkdown','readr','dplyr','ggplot2'))"
    - curl https://raw.githubusercontent.com/InseeFrLab/images-datascience/main/scripts/install-quarto.sh | sudo bash
    - file -bi doc/journee-ssphub/slides/index.qmd
    - quarto render doc/journee-ssphub/slides/index.qmd
    - mv doc/journee-ssphub/slides public
    - mv setup.sh public/setup.sh
    - cat public/index.html
  artifacts:
    paths:
      - public
