

## Construction d'un indice de confiance


```{r fig.width=13, fig.height=5, fig.align="center"}
plot_IC_distrib <- function(data, thresholds, ypos){
  plot <- ggplot(data)+
    ggtitle("Distribution de l’indice de confiance en \nfonction du résultat de la prédiction")+
    geom_histogram(aes(x=Score, fill=Results, y=..density..),binwidth=.01, alpha=.5, position="identity") +
    scale_fill_manual(values=c(Palette_col),labels=c("Mauvaises prédictions", "Bonnes prédictions"))+
    geom_vline(xintercept = thresholds$x, color = rgb(83, 83, 83, maxColorValue = 255))+
    theme_custom()+
    theme(
      plot.title=element_text(size=26, margin=margin(b=0.7, unit='cm')),
      legend.text = element_text(size = 24),
      axis.text.y = element_text(size = 24),
      axis.text.x = element_text(size = 24),
    )+
    annotate("text", x = thresholds$x+0.03, y = ypos, label = c("5%", "10%", "15%", "20%", "25%"), size = 7)
  
  return(plot)
  
}

plot_IC_distrib(IC_distrib, IC_thresholds, 51)


```

- [**Objectif**]{.orange} : [**discriminer**]{.blue2} les *mauvaises* des *bonnes* prédictions.
- [**Indice de confiance retenu**]{.orange} : différence entre les deux probabilités les plus élevées.


## Efficacité de la reprise manuelle


```{r fig.width=13,fig.height=5, fig.align="center"}
Accuracy_reprise <- Accuracy_reprise %>%
      mutate(
           Rate = factor(Rate, levels = paste0(paste(seq(0,25,5)), "%"))
      )
plot_Accuracy_reprise <- function(data){
  plot<- ggplot(data , aes(x=Type, y=Accuracy, fill=Rate))+
    ggtitle("Accuracy en fonction du taux de reprise manuelle effectuée")+
    geom_bar(stat = "identity", position = position_dodge())+
    geom_text(aes(label=round(Accuracy,2)), position=position_dodge(width=0.9), vjust=-0.25, size= 5)+
    scale_fill_manual(values=c(Palette_col))+
    guides(fill=guide_legend(nrow=1, byrow=TRUE))+
    theme_custom()+
    theme(
      text = element_text(size = 16),
      plot.title=element_text(size=26, margin=margin(b=0.7, unit='cm')),
      legend.text = element_text(size = 18),
      axis.text.y = element_text(size = 18),
      axis.text.x = element_text(size = 18),
    )
  return(plot)
}


plot_Accuracy_reprise(Accuracy_reprise)


```

- Optimisation de la reprise manuelle ➨ [**gain de performance**]{.orange}.
