## Context


- [**Several major changes**]{.orange}:
    - [**Internal**]{.blue2}: Revamping of the French company registry, [**Sirene 4**]{.green2}.
    - [**External**]{.blue2}: Implementation of a [**one-stop shop**]{.green2} to declare the creation of a business.

- [**Observation**]{.orange}: [**Sicore**]{.blue2} is no longer a suitable tool ➨ 30% automated coding.

- [**Consequence**]{.orange}: Ideal moment to propose a new methodology for automated NACE coding.

## Data

- [$\approx$ **10 million**]{.orange} observations from Sirene 3 covering the period 2014-2022.
- [**Data labeled**]{.orange} both by Sicore and manually.

- An observation consists of:
    - A [**textual description**]{.red2} of the activity
    - The [**nature of the activity**]{.blue2} -- [NAT]{.green2} (23 categories)
    - The [**type of form**]{.blue2} -- [TYP]{.green2} (15 categories)
    - The [**type of event**]{.blue2} -- [EVT]{.green2} (24 categories)
    - The [**area ($m^2$)**]{.blue2} -- [SUR]{.green2} (4 categories)
  
## Hierarchical structure of NACE Rev. 2

| Level | NACE | Title | Size |
|-------|------|----------------------|-|
| Section     | H     |Transportation and storage|21|
| Division    | 52    |Warehousing and support activities for transportation|88|
| Group      | 522   |Support activities for transportation|272|
| Class      | 5224  |Cargo handling |615|
| **Subclass** | [**5224A**]{.red2} |**Harbour handling**|[**732**]{.orange}|
: {.responsive}
