_target_: torchFastText.model.FastTextModel
model_name: "torchFastText"
preprocessor: PyTorch

model_params:
  embedding_dim: 80
  categorical_embedding_dims: 5
  sparse: False
  direct_bagging: False

train_params:


trainer:
  _target_: trainers.build_trainers.build_lightning_trainer
  num_epochs: 35
  patience_early_stopping: 5

module:
  _target_: models.torch_fasttext.torchFastTextClassifier
