defaults:
  - override /dataset@_global_.dataset: hf_tokenizer
  - override /pre_tokenizer@_global_.pre_tokenizer: bert

tokenizer_type: "WordPiece"
hugging_face: true
num_tokens: 10000
revision: ${revision}
_target_: utils.load_tokenizer.load_tokenizer
