apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-training
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: training-conf-list
        value: '[
          { "EXPERIMENT_NAME": "NACE2008", "MODEL_CLASS": "fasttext", "REVISION": "NAF2008", "START_YEAR": 2025, "DIM": 180, "WS": 5, "LR": 0.2, "EPOCHS": 50, "WORDNGRAMS": 3, "MINN": 3, "MAXN": 4, "MINCOUNT": 3, "BUCKET": 2000000, "LOSS": "ova" },
          { "EXPERIMENT_NAME": "NACE2025", "MODEL_CLASS": "fasttext", "REVISION": "NAF2025", "START_YEAR": 2025, "DIM": 180, "WS": 5, "LR": 0.2, "EPOCHS": 50, "WORDNGRAMS": 3, "MINN": 3, "MAXN": 4, "MINCOUNT": 3, "BUCKET": 2000000, "LOSS": "ova" }
            ]'
  templates:
    - name: main
      # Entrypoint DAG template
      dag:
        tasks:
          - name: run-training-with-params
            template: run-training-wt
            arguments:
              parameters:
                - name: DIM
                  value: "{{item.DIM}}"
                - name: WS
                  value: "{{item.WS}}"
                - name: LR
                  value: "{{item.LR}}"
                - name: EPOCHS
                  value: "{{item.EPOCHS}}"
                - name: WORDNGRAMS
                  value: "{{item.WORDNGRAMS}}"
                - name: MINN
                  value: "{{item.MINN}}"
                - name: MAXN
                  value: "{{item.MAXN}}"
                - name: MINCOUNT
                  value: "{{item.MINCOUNT}}"
                - name: BUCKET
                  value: "{{item.BUCKET}}"
                - name: LOSS
                  value: "{{item.LOSS}}"
                - name: START_YEAR
                  value: "{{item.START_YEAR}}"
                - name: REVISION
                  value: "{{item.REVISION}}"
                - name: MODEL_CLASS
                  value: "{{item.MODEL_CLASS}}"
                - name: EXPERIMENT_NAME
                  value: "{{item.EXPERIMENT_NAME}}"

            # Pass the inputs to the task using "withParam"
            withParam: "{{workflow.parameters.training-conf-list}}"

    # Worker template for task-1
    - name: run-training-wt
      inputs:
        parameters:
          - name: HYDRA_COMMAND
      container:
        image: inseefrlab/codif-ape-train:main
        imagePullPolicy: Always
        command: ["/bin/bash", -c]
        args: ["git clone -b main https://github.com/InseeFrLab/codif-ape-train.git &&\
                cd codif-ape-train/ &&\
                python train.py -m {{inputs}} "
              ]
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: MLFLOW_S3_ENDPOINT_URL
            value: https://minio.lab.sspcloud.fr
          - name: MLFLOW_TRACKING_URI
            value: https://projet-ape-mlflow.user.lab.sspcloud.fr/
          - name: ENTRY_POINT
            value: main
