apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: parallel-training
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: training-conf-list
        value: '[
          { "HYDRA_COMMAND_1":"model.embedding_dim=40,80", "HYDRA_COMMAND_2": "tokenizer.num_tokens=10000,20000,100000"},
          { "HYDRA_COMMAND_1":"model.embedding_dim=180", "HYDRA_COMMAND_2": "tokenizer.num_tokens=10000,20000,100000"}
            ]'
  templates:
    - name: main
      # Entrypoint DAG template
      dag:
        tasks:
          - name: run-training-with-params
            template: run-training-wt
            arguments:
              parameters:
                - name: HYDRA_COMMAND_1
                  value: "{{item.HYDRA_COMMAND_1}}"
                - name: HYDRA_COMMAND_2
                  value: "{{item.HYDRA_COMMAND_2}}"

            # Pass the inputs to the task using "withParam"
            withParam: "{{workflow.parameters.training-conf-list}}"

    # Worker template for task-1
    - name: run-training-wt
      inputs:
        parameters:
          - name: HYDRA_COMMAND_1
          - name: HYDRA_COMMAND_2
      container:
        image: inseefrlab/codif-ape-train:main
        imagePullPolicy: Always
        command: ["/bin/bash", -c]
        args: ["git clone -b main https://github.com/InseeFrLab/codif-ape-train.git &&\
                cd codif-ape-train/ &&\
                mlflow run ~/work/codif-ape-train/ \
                          --env-manager=local
                          -P script_args_1={{inputs.parameters.HYDRA_COMMAND_1}}
                          -P script_args_2={{inputs.parameters.HYDRA_COMMAND_2}}"
              ]
        env:
          # env var for s3 connexion
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: accessKey
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: my-s3-creds
                key: secretKey
          - name: AWS_DEFAULT_REGION
            value: us-east-1
          - name: AWS_S3_ENDPOINT
            value: minio.lab.sspcloud.fr
          - name: MLFLOW_S3_ENDPOINT_URL
            value: https://minio.lab.sspcloud.fr
          - name: MLFLOW_TRACKING_URI
            value: https://projet-ape-mlflow.user.lab.sspcloud.fr/
          - name: MLFLOW_EXPERIMENT_NAME
            value: model_comparison
          - name: ENTRY_POINT
            value: main
