dataset_name: "SoftClassif"
similarity_coefficients:
# one for each level (1 to 5), each element should be in [0, 1]
# See src/datasets/SoftClassifDataset.py for more details
  - 0.01
  - 0.1
  - 0.1
  - 0.1
  - 0.5
